services:
  reproxy-embed:
    build: .
    container_name: reproxy-embed
    hostname: reproxy-embed
    ports:
      - "80:80"
    environment:
      - LISTEN=0.0.0.0:8080
      - ASSETS_LOCATION=/web
